### PR TITLE
Add support for `deploy`-command from drush 10.3

### PR DESCRIPTION
**Pull request by stmh**
This small change will add support for drush's `deploy`-command and its hook-system.

 Closing #106

### CODE REVIEW

**Comment by mikran** [comment]
Looks good, but I think phabalicious should also adopt the drush standardized way to run database updates. Deploy process is now identical except this one part.

currently phabalicious is doing this:
```
$this->runDrush($shell, 'cr -y');
$this->runDrush($shell, 'updb -y');
```

and drush deploy standard is:

```
drush updatedb --no-cache-clear
drush cache:rebuild
```

Doing `cr` before `updb` and doing `updb` with `--no-cache-clear` are most likely a solution to same problem. But I can see cases where the `--no-cache-clear` is better. Doing `cr` before `updb` can lead to some errors that then get resolved by the subsequent `cr`.

**Comment by stmh** [comment]
lets try it out :)

**Comment by stmh** [comment]
@mikran please review

**Review by mikran — CHANGES_REQUESTED** [review]
I've tested it with real case now and it works.

Drush deploy does a cache:rebuild after updb --no-cache-clear and before config-import so that could still be added for exact match with upstream drush.

**Review by mikran — APPROVED** [review]

**Pull request merged**
