### PR TITLE
Initial implementation of new command `docker-compose`

### PR DESCRIPTION
**Pull request by stmh**
Here's the initial implementation of the docker-compose command. Documentation is missing and we might need to handle errors a little better.

### CODE REVIEW

**Comment by mikran** [comment]
Interactive shell is not working, Executing commands with `phab -cmbb -vvv docker-compose -- exec web ls` gives

>the input device is not a TTY

**Comment by stmh** [comment]
Then we should use a similar approach as drush is using. Basically we pass the request to the methods so they can react to it -- the methods will return the command line to execute which will then be executed by the command with an interactive shell.

**Comment by stmh** [comment]
I reworked the implementation to use an interactive shell to run docker-compose. unfortunately not so easy. But I could refactor drush and drupal-console using the same code, yay.

**Review by mikran — APPROVED** [review]
this is great!

**Pull request merged**
