### PR TITLE
3.8.0

### LINKED ISSUE #174: New version notification isn't relevant when you're already doing self-update
Total nitpick ;)

But when you're doing `phab self-update`, it's redundant to say 'Version 3.6.13 of phabalicious is available. etc'.

### LINKED ISSUE #181: Do not run reset after `phab copy-from <xxx> files`
It is not needed to run reset after copy-from copied only the files.

### LINKED ISSUE #211: admin password change from reset happens too early
The reset task was failing with "Class not found" error because of invalid cache. This got resolved by running `drush cr` first and then repeating the `phab reset`.

So maybe the tasks can be reordered and password reset can be last?

### LINKED ISSUE #214: Add separators to date parts in database filename dumped by get:sql-dump
The `get:sql-dump` command produces a file named for the host and the date when it was created: 

> main-preview.20211214101222.sql.gz

The 20211214101222 suffix is a date and time in human format, but it would be easier to figure out that's what it is, and to read it if it had separators, eg.

> main-preview.2021-12-14-1012-22.sql.gz

### PR DESCRIPTION
**Pull request by stmh**
### Changed:
* Minimum PHP requirement: 7.3

### New:
* Added script- and scaffold-callbacks for encryption and decryption using `defuse/php-encryption`
* Added new callbacks for getting a file from 1password-cli / -connect
* Obfuscate passwords in log-outputs

### Fixed
* Do not run reset when only running copy-from files (Fixes #181)
* Set admin-password after config import, (Fixes #211)
* Do not run `reset`-command after `copy-from files` (Fixes #180)
* Do not check for updates when running `self-update` (Fixes #174)
* Human readable date and time in generated file names (Fixes #214)

### CODE REVIEW

**Comment by mikran** [comment]
I think something is off with the self-update in this branch, it is displaying available update as

>Version 3.7.6.0 of phabalicious is available.

**Comment by stmh** [comment]
Thanks for spotting this, should be fixed with the latest commits.

**Comment by mikran** [comment]
found regression from `k8s scaffold`

3.8-beta gives

```
In ConfigurationService.php line 481:
                                                                                     
  Could not resolve inheritance from `inheritsFrom: ./scaffold/scaffold/base.yml`!   
                                                                                     
  Possible values:                                                                   
  -                                                                                  
                                                                                     
```

3.7.7 works ok

there is no `./scaffold/scaffold/base.yml` only `./scaffold/base.yml` so extra `/scaffold` is added in 3.8-beta

**Comment by stmh** [comment]
Thanks @mikran for reporting the issue.

Phab 3.8 now resolves relative paths when inheriting data the "right way". This might break for certain setups, but your case was indeed a regression. Should be fixed with my latest commit

**Pull request merged**
