### PR TITLE
Existing config install

### PR DESCRIPTION
**Pull request by mikran**
re #45 

Here as my attempt at fixing this.

### CODE REVIEW

**Comment by stmh** [comment]
Hi @mikran 

Thanks for your MR, highly appreciated.

Changes are looking good, but one thing: I wouldnt remove running the reset task after the install task, as the reset task might be used to "reset" an installation to a particular environment, e.g. sanitizing prod credentials for local development or enabling shield, whatever. And it might be required by existing installations like D7 or other frameworks which do not have configuration management.

I'd use the `$context`-object to set a flag by the install task when a configuration is available and used for installation and be read when running the configuration import on reset. As the context gets resetted when running a new task, make sure to use `$context->setResult(key, value)` and `$context->getresult(key, defaultValue)` as only results will be kept when running multiple tasks.

**Comment by stmh** [comment]
Nevermind, will merge to develop and cherry-pick for a hotfix. thanks!

**Comment by mikran** [comment]
I've restored the reset.

I didn't understand why its needed in context that config import was done. Sure reset does some things like setting the uuid that is no longer necessary, but it should be made optional and removed from .fabile too to get any benefits from the change.

**Comment by stmh** [comment]
You can enhance the reset task (basically every tasks) with scripts per type and/ or per host. We use this for example to enable shield on dev-instances or set some configuration for non-prod instances (e.g. disabling creditcrad handling, stuff like that) Sure, you can use config_split for that, but it might be still useful for some occasions. More importantly removing the reset task will change existing behaviour.

**Comment by mikran** [comment]
> You can enhance the reset task (basically every tasks) with scripts per type and/ or per host. We use this for example to enable shield on dev-instances or set some configuration for non-prod instances (e.g. disabling creditcrad handling, stuff like that) Sure, you can use config_split for that, but it might be still useful for some occasions. More importantly removing the reset task will change existing behaviour.

I totally agree that reset is used for all that. But with context I ment the $context -object that you mentioned in your last comment, that part I did not understand :)

**Comment by stmh** [comment]
:) sorry!

What you can do to signalize the reset task to *not* run the config-import and not to set the uuid is to set a flag on the context-object.
So in install-task implementation of drush do sth like `$context->setResult('ignoreConfigImport', true)` and then check in the reset-task-implemenation if that flag is set, e.g. `if ($context->getResult('ignoreConfigImport', false)) { ... }`

The context transports variables into the methods from eg. the command-implementations and holds any results which is used in methods or in commands. There is one caveat though: The context get cloned before passing it to a new method-implementation, only results are persistant, they get merged after each method-implementation get executed. (for details have a look into https://github.com/factorial-io/phabalicious/blob/409804c3c5f79e56fa7dd276a0fa379e9f853a0a/src/Method/MethodFactory.php#L170)

**Comment by mikran** [comment]
I was too focused on getting the secondary use case of existing config install to work correctly so I totally forgot the original issue of no config to import at all. Yes! I'll do that on Monday!

**Comment by stmh** [comment]
hi @mikran,

I'll merge this MR into a dedicated branch and do some testing there. As the current branch has some conflicts it makes it easier for me.

**Pull request merged**
