### PR TITLE
cleanup kube folder before scaffold

### LINKED ISSUE #161: cleanup kube folder to prevent leftovers which might be applied accidently
when there are leftovers in the kube folder there is  a chance, that these leftovers are applied to a kubernetes cluster. To prevent this, cleanup the folder before running the scaffolding.

### PR DESCRIPTION
**Pull request by stmh**
hi @mikran 

please review these changes. Thes changes should clean up the kube folder before scaffolding new files into it.

Fixes #161

### CODE REVIEW

**Review by mikran — APPROVED** [review]
looks good to me

**Comment by stmh** [comment]
hi @mikran 

Thanks, can you add a review and approve the changes?

**Review by mikran — APPROVED** [review]

**Comment by mikran** [comment]
> hi @mikran
> 
> Thanks, can you add a review and approve the changes?

I approved it already, but it seems my approve is not sufficient, it says " At least 1 approving review is required by reviewers with write access. "

**Comment by stmh** [comment]
thanks, fixed the permission issue.

**Pull request merged**
