### PR TITLE
Feature/database enhancements

### PR DESCRIPTION
**Pull request by stmh**
Adds dedicated commands for the new database methods:

* `db:install`
* `db:drop`
* ` db:shell`
* `db:shell:command`

The latter two command are working similar to the `shell` command and connects the user to a running mysql-client or print the command instead

Some smaller enhancements and bugfixes.

### CODE REVIEW

**Comment by stmh** [comment]
The last commit contains a change in how sql dumps are created to mimic drushs behavior better: the complete structure of all tables is exported, then the data off all tables which are not excluded. So that all tables will be created when imported..

**Review by mikran — CHANGES_REQUESTED** [review]
I did manual testing and I can not get most these commands to work, `db:drop` is the only one that worked (or at least it reported "[OK] Database-command `drop` executed successfully!")

`shell:command` and `get:sql-dump` are both working in the project I was testing with, `needs` is:

```
    needs:
      - k8s
      - files
      - mattermost
      - restic
      - mysql
```

`db:shell:command` and `db:shell` are failing with

```
In KubectlShellProvider.php line 93:

  Could not get shell, as podForCli is empty!
```

`db:install` fails with

```
In CommandResult.php line 51:

  Could not connect to database!
```

**Comment by stmh** [comment]
thanks @mikran 

Should be fixed now. Can you think on any circumstance where you want to have access to the database without that the application itself is running (be it via docke-compose or via k8s)? As we are always using part of the app as a jump host i cant think of a scenario here.

Would be great if you can retest it

**Review by mikran — APPROVED** [review]
Great, Now it works!

**Pull request merged**
